# Common to all builds in the build matrixs
os: linux
language: python # This lets us use newer python versions from virtualenv
sudo: false
cache:
  apt: true
  pip: true
  directories:
    # commented out - we want to get fresh overpass file each time
    #- /tmp # cache any previously downloaded .osm files
  timeout: 1000
compiler: clang

python:
  - '3.6'
  - '3.5'
  - '3.4'

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
      - postgis
      - osm2pgsql

env:
  global:
    - ON_TRAVIS=true
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - APP_SETTINGS=app_config.DevelopmentConfig
    - DATABASE_URL=postgresql://test_user:test_password@localhost/testing_db
    - TESTDATABASE_URL=postgresql://test_user:test_password@localhost/testing_db
    - LECHAT=bonjour

email:
  - pierrealix@kartoza.com

matrix:
  fast_finish: true
  include:
    - python: '3.6'
      env: TRAVIS_CONFIG=PYTHON3
    - python: '3.5'
      env: TRAVIS_CONFIG=PYTHON3
    - python: '3.4'
      env: TRAVIS_CONFIG=PYTHON3

  exclude:
    - python: '3.6'
    - python: '3.5'
    - python: '3.4'

git:
  depth: 30

before_install:

install:
  - pip install coveralls
  - pip install -r flask_project/requirements.txt

sudo: true

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'test_password';" -U postgres
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE testing_db to test_user;"
  - psql -U postgres -c "ALTER USER test_user CREATEDB;"
  - psql -U postgres -c "create extension postgis" -d testing_db

script:
  - cd flask_project && make pep8
  - nosetests
  - echo "is echo working?"

deploy:
  - provider: elasticbeanstalk
    access_key_id:
      secure: "eIzodiAQ/5pfkRhEbeDsawtxlBLIGz+Wt9s+2YP9se/VDFwzH1L2Yf/jhmwyoH6MzTtiau8X8gJIQbuXjJFLMDJgk1QPUKYW69rfv+gvpgvGH4frIW6jp9y6OUutJtX/D7llWV6JhV38jWC1CNtosWf0VRHbX3yyvI7FUV8w2wkl70x5UjrofYyAD2picaHTDISO5KatxUm3bHG0koHuFOatezP5qZFjq5Qd0nYc8v6/uL1de2CCt0iHPqjFJqlqLgmKWa2xMHtBPY6I/IByDV4mMZAdi1AH6YuAQOlTBS5lhUyXSpimqRBXmd9bHsQwwj9z582UD3GOzltRt8OQdo/5ikmzqusXahKz4+cyvAPQH26BjilcfSkqp4s5Utfb3KjMNVyx4j8kZoQn+MqYO2ZKhteIoj6l8kBSu9knAL5CSpsjOm1Mx0Iy5x8W5Ct+EZFI9FdpZu/s0GDr2ZbMTrpBkvJM4D+98sTOSvGSVQBq8sbjh9PLyE8tWWNBlmVkGgubMNRM9Oe3kF20mzv9Hx7pV0cWdc6rxKAC8Iorw0IhrAibd4CzaY1CPWV40kJ1qsu+Ih0Om9rOGN4DcVC1vAPIWBXTwFXJbCV1C6HmVA4an9/6G3z63wTHc7q5/WnU1uSgWP0Id4XtZPYB6sDNz9T3gR+t3LRMXYMfSTcxjKk="
    secret_access_key:
      secure: "NQKFXWaUAdoS5jSvFt2TF4u63gb9y0HPrTAxuXnmVCSPS/2RMj98r0jjOINbw9ZqIOdSNnsvIPcjljR5tEpeg51fvzr6Ud/FybAC6tw2+yCIpc8TuchiP08E0phdS0vzmAzPd6XAoVSgfOqJKBFnTzeGavgVlFgChwBz9Dy1PRu+1R3vkhlB15B8OC0EVCHS2D0vdZUu9hNSSqq3oxr0IJdLFwERyHuR/t28o3DQm/RZ0C36TWDiwdkkeQasl9wLnmCBi0f+NpDJjx7je7ALUIENZcLUyR2a7mf01+WVH+Z0JWwwxavviUhjnFyaLFpJ55fjwHvLeIDbioxx070Thhr4MCXy+IsXy8VjhnnUrdJry+2kA9gB0fdG5r8bnoZrhgBvCgkhBOynO3WPdTwunNpfFYO444JssgC2r8qtH/ApBp9/YtWJyOIrt14bz/XwcN7wURdVtrqKYuvlqqBZAELRIdOvw299ve3lBIULavj7RDibLJJFNUWDeX0kOT/ixszG9orFSEcVELIU7n7hklSTwZi73RBwsG8PRlNdLYYzWeZNUOYWqZi/1XtLH+RnKmTzWwwqTlbcs7iPuMKYyPrnd+hPS8VzRt1vm1ywtFx0Q+Dge8kpGxvthGhgxOY0LUcv9HRLKphQazIPm0PKWXJA8xZRuRdZE1P0WYOQNlQ="
    region: "us-west-2"
    app: "field-campaigner-eb"
    env: "field-campaigner-eb-dev"
    bucket_name: fieldcampaigner-eb-deployments
    zip_file: build.zip
    on:
      branch: aws-eb

  - provider: elasticbeanstalk
    access_key_id:
      secure: "eIzodiAQ/5pfkRhEbeDsawtxlBLIGz+Wt9s+2YP9se/VDFwzH1L2Yf/jhmwyoH6MzTtiau8X8gJIQbuXjJFLMDJgk1QPUKYW69rfv+gvpgvGH4frIW6jp9y6OUutJtX/D7llWV6JhV38jWC1CNtosWf0VRHbX3yyvI7FUV8w2wkl70x5UjrofYyAD2picaHTDISO5KatxUm3bHG0koHuFOatezP5qZFjq5Qd0nYc8v6/uL1de2CCt0iHPqjFJqlqLgmKWa2xMHtBPY6I/IByDV4mMZAdi1AH6YuAQOlTBS5lhUyXSpimqRBXmd9bHsQwwj9z582UD3GOzltRt8OQdo/5ikmzqusXahKz4+cyvAPQH26BjilcfSkqp4s5Utfb3KjMNVyx4j8kZoQn+MqYO2ZKhteIoj6l8kBSu9knAL5CSpsjOm1Mx0Iy5x8W5Ct+EZFI9FdpZu/s0GDr2ZbMTrpBkvJM4D+98sTOSvGSVQBq8sbjh9PLyE8tWWNBlmVkGgubMNRM9Oe3kF20mzv9Hx7pV0cWdc6rxKAC8Iorw0IhrAibd4CzaY1CPWV40kJ1qsu+Ih0Om9rOGN4DcVC1vAPIWBXTwFXJbCV1C6HmVA4an9/6G3z63wTHc7q5/WnU1uSgWP0Id4XtZPYB6sDNz9T3gR+t3LRMXYMfSTcxjKk="
    secret_access_key:
      secure: "NQKFXWaUAdoS5jSvFt2TF4u63gb9y0HPrTAxuXnmVCSPS/2RMj98r0jjOINbw9ZqIOdSNnsvIPcjljR5tEpeg51fvzr6Ud/FybAC6tw2+yCIpc8TuchiP08E0phdS0vzmAzPd6XAoVSgfOqJKBFnTzeGavgVlFgChwBz9Dy1PRu+1R3vkhlB15B8OC0EVCHS2D0vdZUu9hNSSqq3oxr0IJdLFwERyHuR/t28o3DQm/RZ0C36TWDiwdkkeQasl9wLnmCBi0f+NpDJjx7je7ALUIENZcLUyR2a7mf01+WVH+Z0JWwwxavviUhjnFyaLFpJ55fjwHvLeIDbioxx070Thhr4MCXy+IsXy8VjhnnUrdJry+2kA9gB0fdG5r8bnoZrhgBvCgkhBOynO3WPdTwunNpfFYO444JssgC2r8qtH/ApBp9/YtWJyOIrt14bz/XwcN7wURdVtrqKYuvlqqBZAELRIdOvw299ve3lBIULavj7RDibLJJFNUWDeX0kOT/ixszG9orFSEcVELIU7n7hklSTwZi73RBwsG8PRlNdLYYzWeZNUOYWqZi/1XtLH+RnKmTzWwwqTlbcs7iPuMKYyPrnd+hPS8VzRt1vm1ywtFx0Q+Dge8kpGxvthGhgxOY0LUcv9HRLKphQazIPm0PKWXJA8xZRuRdZE1P0WYOQNlQ="
    region: "us-west-2"
    app: "field-campaigner-eb"
    env: "staging"
    bucket_name: fieldcampaigner-eb-deployments
    zip_file: build.zip
    on:
      branch: develop

after_deploy:
  - echo "done deploying"

after_script:
  - coveralls
  - echo "build done."
