# Common to all builds in the build matrixs
os: linux
language: python # This lets us use newer python versions from virtualenv
sudo: false
cache:
  apt: true
  pip: true
  directories:
    # commented out - we want to get fresh overpass file each time
    #- /tmp # cache any previously downloaded .osm files
  timeout: 1000
compiler: clang

python:
  - '3.6'
  - '3.5'
  - '3.4'

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
      - postgis
      - osm2pgsql

env:
  global:
    - ON_TRAVIS=true
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - APP_SETTINGS=app_config.DevelopmentConfig
    - DATABASE_URL=postgresql://test_user:test_password@localhost/testing_db
    - TESTDATABASE_URL=postgresql://test_user:test_password@localhost/testing_db
    - LECHAT=bonjour

email:
  - pierrealix@kartoza.com

matrix:
  fast_finish: true
  include:
    - python: '3.6'
      env: TRAVIS_CONFIG=PYTHON3
    - python: '3.5'
      env: TRAVIS_CONFIG=PYTHON3
    - python: '3.4'
      env: TRAVIS_CONFIG=PYTHON3

  exclude:
    - python: '3.6'
    - python: '3.5'
    - python: '3.4'

git:
  depth: 30

before_install:

install:
  - pip install coveralls
  - pip install -r flask_project/requirements.txt

sudo: true

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD 'test_password';" -U postgres
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE testing_db to test_user;"
  - psql -U postgres -c "ALTER USER test_user CREATEDB;"
  - psql -U postgres -c "create extension postgis" -d testing_db

script:
  - cd flask_project && make pep8
  - nosetests
  - echo "is echo working?"

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: AKIAJ5EPAW4BWD6M3WVA
  secret_access_key: 
    secure: "THU/sa2rNPH2AxhKijVWPfqTHeHOpi93QQ5czE7mxy3hfs1zQfJrrWswH4ADcyuyYwlunN3mcVMSzI7/bz+3pBmyquBnkQbtNJuRMaSkYB3cNgRLgQdgpM34dVrUgauCPxHyxRecL8onvMIL8fRCe/lQo+r3CG3KXxsp+LI/T7Fkp0MSUaeo2/5ymhA1nGoDfTcPuybTGFN4Jg5A4r4bN6qN1Vccg2bXucisIlo7OZzpLjLYuXK1InSu4BlIC2Ayye31HOjrzfprAndPnGWoHh3kP7261AFW2OEhElwmhl2J3fc3+nr6bXjf64aEK00zxDkYhKyqti/IRDJ6R/d2r0zh7557mWBU0etUXZ3r+JYNLiMcmjqp6Rw+TaY5cnJHJXl15az5Sf5dfdRhdJsAnXkYF/0WF4Omm234Npca4/p2tgBjV66iasKcgyypf8cl5B40wv7oas7ffefxz8a/orhm8W+Ae3CO7W4jgBddGi/nSd5c7pMhWeYAdzAYC5M42UN+3Nub1X/Q1IarXrsM0AJwaFOfGhSq3V4G4uROV81be0izInm4tr7r480YqBGSEE+fqYmddJ0h1fCtKPvAXqq6nTu86U3Mz5kDYvXzdqteYlcIkryV+2wiHQ369EcCkIutGrEa88I4Cgg1KlyU8Iaz46zI70yif5df3eqwheE="
  region: "us-west-2"
  app: "field-campaigner-eb"
  env: "field-campaigner-eb-dev" # staging
  bucket_name: "elasticbeanstalk-us-west-2-142767531394"
  # bug: on: becomes true:
  # on:
  #   repo: pierrealix/field-campaigner
  #   branch: aws-eb

branches:
  only:
    - aws-eb

after_deploy:
  - echo "done deploying"

after_script:
  - coveralls
  - echo "build done."
